# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous integration

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      env:
        cache-name: cache-gradle
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
