# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 25
        fetch-tags: 'true'
    - name: Set up JDK
      uses: actions/setup-java@v4.3.0
      with:
        distribution: 'adopt'
        java-version-file: '.tool-versions'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        add-job-summary-as-pr-comment: 'always'
    - name: Build with Gradle
      run: ./gradlew -Dorg.gradle.welcome=never build
