name: Dependency Submission

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'adopt'
          java-version-file: '.tool-versions'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          artifact-retention-days: 14